# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6a5dd0b7beb92075f2013705ebe5cb162585c7bfa2ff43400d86ad3857177303cd07d52dcf46c0eea921ee66ce74a216f3962f616d1d837628348358d18300b

test:
  secret_key_base: a348f7b79dadc8679733b1a94692167f6b603ef8daa7a67e82d83b350703aab27a090cd60e216cd5a44d5c851088771965209a45684742dae9c234dfcbdfd93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
